/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => LinianPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/api.ts
var import_obsidian = require("obsidian");

// src/constants.ts
var DEFAULT_SETTINGS = {
  apiKey: "",
  enablePriorityIcons: true,
  enableAssigneeAvatars: true,
  maxCacheSize: 1e3,
  autoRefresh: true,
  staleAfterMs: 6 * 60 * 60 * 1e3
  // 6 hours
};
var normalizeIdentifier = (raw) => raw.trim().toUpperCase();
var SHORTCODE_PATTERN = "\\[(L_)?([A-Za-z]+(?:-[A-Za-z]*)?-\\d+)\\]";
var LINEAR_SHORTCODE_REGEX = new RegExp(SHORTCODE_PATTERN, "gi");
var createShortcodeRegex = () => new RegExp(SHORTCODE_PATTERN, "gi");
var GRAPHQL_QUERIES = {
  ISSUE_BY_IDENTIFIER: `
		query FindIssue($teamKey: String!, $number: Float!) {
			issues(filter: { 
				team: { key: { eq: $teamKey } }, 
				number: { eq: $number } 
			}) {
				nodes {
					id
					identifier
					title
					description
					url
					priority
					state {
						id
						name
						color
					}
					assignee {
						id
						name
						avatarUrl
					}
					team {
						id
						key
						name
					}
					comments {
						nodes {
							id
						}
					}
					createdAt
					updatedAt
				}
			}
		}
	`,
  ORGANIZATION_TEAMS: `
		query Teams {
			teams {
				nodes {
					id
					name
					key
				}
			}
		}
	`
};
var PRIORITY_ICONS = {
  0: "\u26AA",
  // No priority
  1: "\u{1F535}",
  // Low
  2: "\u{1F7E1}",
  // Medium
  3: "\u{1F7E0}",
  // High
  4: "\u{1F534}"
  // Urgent
};
var PRIORITY_LABELS = {
  0: "No priority",
  1: "Low",
  2: "Medium",
  3: "High",
  4: "Urgent"
};

// src/api.ts
var LINEAR_ENDPOINT = "https://api.linear.app/graphql";
var LinearAPIService = class {
  constructor(apiKey) {
    this.apiKey = apiKey;
  }
  updateApiKey(apiKey) {
    this.apiKey = apiKey;
  }
  /**
   * Fetch a single issue by identifier. Uses Obsidian's `requestUrl` so the
   * request runs in the main process — no CORS/CSP restrictions, works on
   * mobile.
   */
  async fetchIssue(identifier) {
    var _a, _b, _c, _d, _e;
    const match = normalizeIdentifier(identifier).match(/^([A-Z]+)-(\d+)$/);
    if (!match)
      return { status: "not-found" };
    const teamKey = match[1];
    const number = parseInt(match[2], 10);
    let response;
    try {
      response = await (0, import_obsidian.requestUrl)({
        url: LINEAR_ENDPOINT,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: this.apiKey
        },
        body: JSON.stringify({
          query: GRAPHQL_QUERIES.ISSUE_BY_IDENTIFIER,
          variables: { teamKey, number }
        }),
        throw: false
      });
    } catch (e) {
      return { status: "unreachable" };
    }
    if (response.status < 200 || response.status >= 300) {
      return { status: "unreachable" };
    }
    const payload = response.json;
    if (payload.errors) {
      return { status: "unreachable" };
    }
    const node = (_c = (_b = (_a = payload.data) == null ? void 0 : _a.issues) == null ? void 0 : _b.nodes) == null ? void 0 : _c[0];
    if (node) {
      const { comments, ...issue } = node;
      issue.commentCount = (_e = (_d = comments == null ? void 0 : comments.nodes) == null ? void 0 : _d.length) != null ? _e : 0;
      return { status: "ok", issue };
    }
    return { status: "not-found" };
  }
  /** Used by the settings "Test Connection" button. */
  async getTeams() {
    var _a, _b, _c;
    try {
      const response = await (0, import_obsidian.requestUrl)({
        url: LINEAR_ENDPOINT,
        method: "POST",
        headers: {
          "Content-Type": "application/json",
          Authorization: this.apiKey
        },
        body: JSON.stringify({ query: GRAPHQL_QUERIES.ORGANIZATION_TEAMS }),
        throw: false
      });
      if (response.status < 200 || response.status >= 300)
        return [];
      const payload = response.json;
      return (_c = (_b = (_a = payload.data) == null ? void 0 : _a.teams) == null ? void 0 : _b.nodes) != null ? _c : [];
    } catch (e) {
      return [];
    }
  }
};

// src/renderer.ts
var LinearRenderer = class {
  constructor(settings) {
    this.settings = settings;
  }
  updateSettings(settings) {
    this.settings = settings;
  }
  /** Build the inline issue link from a cached snapshot. */
  createIssueElement(entry, displayMode = "compact") {
    var _a;
    const { issue } = entry;
    const issueEl = document.createElement("a");
    issueEl.className = "linian-issue-link";
    if (displayMode === "expanded") {
      issueEl.classList.add("linian-issue-link--expanded");
    }
    if (entry.status !== "fresh") {
      issueEl.classList.add("linian-issue-link--cached");
    }
    issueEl.href = issue.url;
    issueEl.setAttribute(
      "aria-label",
      `Linear issue: ${issue.identifier} - ${issue.title}`
    );
    const contentEl = document.createElement("span");
    contentEl.className = "linian-issue-content";
    const showPriority = this.settings.enablePriorityIcons && issue.priority !== void 0;
    if (showPriority && displayMode === "compact") {
      const priorityEl = document.createElement("span");
      priorityEl.className = "linian-priority-icon";
      priorityEl.textContent = PRIORITY_ICONS[issue.priority] || PRIORITY_ICONS[0];
      priorityEl.setAttribute(
        "title",
        PRIORITY_LABELS[issue.priority] || PRIORITY_LABELS[0]
      );
      contentEl.appendChild(priorityEl);
    }
    if (displayMode === "expanded") {
      const leadingDot = document.createElement("span");
      leadingDot.className = "linian-expanded-dot linian-expanded-dot--leading";
      leadingDot.textContent = "\u25CF";
      leadingDot.style.color = issue.state.color;
      contentEl.appendChild(leadingDot);
      const titleEl = document.createElement("span");
      titleEl.className = "linian-issue-title";
      titleEl.textContent = issue.title;
      contentEl.appendChild(titleEl);
      const trailingDot = document.createElement("span");
      trailingDot.className = "linian-expanded-dot linian-expanded-dot--trailing";
      trailingDot.textContent = "\u2022";
      trailingDot.style.color = issue.state.color;
      contentEl.appendChild(trailingDot);
    } else {
      const identifierEl = document.createElement("span");
      identifierEl.className = "linian-issue-identifier";
      identifierEl.textContent = issue.identifier;
      contentEl.appendChild(identifierEl);
      const statusEl = document.createElement("span");
      statusEl.className = "linian-status-indicator";
      statusEl.style.backgroundColor = issue.state.color;
      statusEl.setAttribute("title", issue.state.name);
      contentEl.appendChild(statusEl);
    }
    issueEl.appendChild(contentEl);
    if (displayMode === "compact" && this.settings.enableAssigneeAvatars && ((_a = issue.assignee) == null ? void 0 : _a.avatarUrl)) {
      const avatarEl = document.createElement("img");
      avatarEl.className = "linian-assignee-avatar";
      avatarEl.src = issue.assignee.avatarUrl;
      avatarEl.alt = issue.assignee.name;
      avatarEl.setAttribute("title", `Assigned to ${issue.assignee.name}`);
      issueEl.appendChild(avatarEl);
    }
    return issueEl;
  }
  createLoadingElement(identifier, displayMode = "compact") {
    const loadingEl = document.createElement("span");
    loadingEl.className = "linian-loading";
    if (displayMode === "expanded") {
      loadingEl.classList.add("linian-loading--expanded");
      loadingEl.textContent = "Loading issue\u2026";
    } else {
      loadingEl.textContent = identifier;
    }
    loadingEl.setAttribute("title", "Loading Linear issue\u2026");
    return loadingEl;
  }
  /** Shown only when there is no cached snapshot and Linear is unreachable. */
  createUnavailableElement(identifier, displayMode = "compact") {
    const el = document.createElement("span");
    el.className = "linian-unavailable";
    if (displayMode === "expanded") {
      el.classList.add("linian-unavailable--expanded");
    }
    el.textContent = identifier;
    el.setAttribute(
      "title",
      "Not cached yet and Linear is currently unreachable."
    );
    return el;
  }
};

// src/cache.ts
var import_obsidian2 = require("obsidian");
var CACHE_FILE = "issue-cache.json";
var CACHE_VERSION = 1;
var IssueCacheStore = class {
  constructor(plugin, maxSize) {
    this.plugin = plugin;
    this.entries = /* @__PURE__ */ new Map();
    this.maxSize = maxSize;
    this.persist = (0, import_obsidian2.debounce)(() => void this.flush(), 1500, false);
  }
  setMaxSize(maxSize) {
    this.maxSize = maxSize;
  }
  get path() {
    return (0, import_obsidian2.normalizePath)(`${this.plugin.manifest.dir}/${CACHE_FILE}`);
  }
  /** Load persisted snapshots from disk. Safe to call once on plugin load. */
  async load() {
    try {
      const adapter = this.plugin.app.vault.adapter;
      if (!await adapter.exists(this.path))
        return;
      const raw = await adapter.read(this.path);
      const parsed = JSON.parse(raw);
      if (!parsed || parsed.version !== CACHE_VERSION || !parsed.entries)
        return;
      this.entries = new Map(Object.entries(parsed.entries));
    } catch (e) {
      this.entries = /* @__PURE__ */ new Map();
    }
  }
  async flush() {
    try {
      const data = {
        version: CACHE_VERSION,
        entries: Object.fromEntries(this.entries)
      };
      await this.plugin.app.vault.adapter.write(
        this.path,
        JSON.stringify(data)
      );
    } catch (e) {
    }
  }
  /** Force any pending write immediately (used on unload). */
  async flushNow() {
    await this.flush();
  }
  get(rawKey) {
    return this.entries.get(normalizeIdentifier(rawKey));
  }
  /** Store a freshly-fetched issue and mark it fresh. */
  set(rawKey, issue) {
    const key = normalizeIdentifier(rawKey);
    const now = Date.now();
    const entry = {
      issue,
      fetchedAt: now,
      lastAttempt: now,
      status: "fresh"
    };
    this.entries.set(key, entry);
    this.evictIfNeeded();
    this.persist();
    return entry;
  }
  /**
   * Record a failed revalidation without discarding the stored snapshot.
   * Returns the retained entry (if any) so callers can keep rendering it.
   */
  markStale(rawKey, status) {
    const key = normalizeIdentifier(rawKey);
    const entry = this.entries.get(key);
    if (!entry)
      return void 0;
    entry.lastAttempt = Date.now();
    entry.status = status;
    this.persist();
    return entry;
  }
  clear() {
    this.entries.clear();
    this.persist();
  }
  size() {
    return this.entries.size;
  }
  evictIfNeeded() {
    if (this.entries.size <= this.maxSize)
      return;
    const sorted = [...this.entries.entries()].sort(
      (a, b) => a[1].fetchedAt - b[1].fetchedAt
    );
    const overflow = this.entries.size - this.maxSize;
    for (let i = 0; i < overflow; i++) {
      this.entries.delete(sorted[i][0]);
    }
  }
};

// src/issue-controller.ts
var IssueController = class {
  constructor(api, cache, renderer, getSettings, openCard) {
    this.api = api;
    this.cache = cache;
    this.renderer = renderer;
    this.getSettings = getSettings;
    this.openCard = openCard;
    this.inFlight = /* @__PURE__ */ new Map();
    this.revalidatedThisSession = /* @__PURE__ */ new Set();
  }
  render(container, rawKey, mode) {
    const key = normalizeIdentifier(rawKey);
    const cached = this.cache.get(key);
    if (cached) {
      this.paint(container, cached, mode);
      if (this.shouldRevalidate(cached)) {
        void this.ensureFresh(key).then((entry) => {
          if (entry)
            this.paint(container, entry, mode);
        });
      }
      return;
    }
    container.replaceChildren(this.renderer.createLoadingElement(key, mode));
    void this.ensureFresh(key).then((entry) => {
      if (entry)
        this.paint(container, entry, mode);
      else
        container.replaceChildren(
          this.renderer.createUnavailableElement(key, mode)
        );
    });
  }
  paint(container, entry, mode) {
    const el = this.renderer.createIssueElement(entry, mode);
    el.addEventListener("click", (evt) => {
      if (evt.ctrlKey || evt.metaKey || evt.button === 1)
        return;
      evt.preventDefault();
      this.openCard(entry);
    });
    container.replaceChildren(el);
  }
  shouldRevalidate(entry) {
    const settings = this.getSettings();
    if (!settings.autoRefresh)
      return false;
    const key = normalizeIdentifier(entry.issue.identifier);
    if (this.revalidatedThisSession.has(key))
      return false;
    return Date.now() - entry.fetchedAt >= settings.staleAfterMs;
  }
  /** Fetch once per id per session, deduped across concurrent callers. */
  ensureFresh(rawKey) {
    const key = normalizeIdentifier(rawKey);
    const existing = this.inFlight.get(key);
    if (existing)
      return existing;
    const promise = this.doFetch(key).finally(() => {
      this.inFlight.delete(key);
      this.revalidatedThisSession.add(key);
    });
    this.inFlight.set(key, promise);
    return promise;
  }
  async doFetch(key) {
    const result = await this.api.fetchIssue(key);
    switch (result.status) {
      case "ok":
        return this.cache.set(key, result.issue);
      case "not-found":
        return this.cache.markStale(key, "inaccessible");
      case "unreachable":
        return this.cache.markStale(key, "unreachable");
    }
  }
  /**
   * Force the next render of every cached issue to revalidate (manual
   * "Refresh" command). Does not fetch here — repaint happens as notes
   * re-render.
   */
  resetSessionGuard() {
    this.revalidatedThisSession.clear();
  }
};

// src/card.ts
var import_obsidian3 = require("obsidian");
function formatRelative(ts) {
  const diff = Date.now() - ts;
  const min = Math.round(diff / 6e4);
  if (min < 1)
    return "just now";
  if (min < 60)
    return `${min} minute${min === 1 ? "" : "s"} ago`;
  const hrs = Math.round(min / 60);
  if (hrs < 24)
    return `${hrs} hour${hrs === 1 ? "" : "s"} ago`;
  const days = Math.round(hrs / 24);
  return `${days} day${days === 1 ? "" : "s"} ago`;
}
var IssueCard = class extends import_obsidian3.Modal {
  constructor(app, entry) {
    super(app);
    this.entry = entry;
    this.component = new import_obsidian3.Component();
  }
  onOpen() {
    const { contentEl } = this;
    const { issue, status, fetchedAt } = this.entry;
    contentEl.addClass("linian-card");
    const header = contentEl.createDiv({ cls: "linian-card-header" });
    header.createEl("span", {
      cls: "linian-card-identifier",
      text: issue.identifier
    });
    const statusPill = header.createEl("span", {
      cls: "linian-card-status",
      text: issue.state.name
    });
    statusPill.style.backgroundColor = issue.state.color;
    contentEl.createEl("h3", { cls: "linian-card-title", text: issue.title });
    const meta = contentEl.createDiv({ cls: "linian-card-meta" });
    meta.createEl("span", {
      cls: "linian-card-team",
      text: issue.team.name
    });
    if (issue.assignee) {
      meta.createEl("span", {
        cls: "linian-card-assignee",
        text: `@${issue.assignee.name}`
      });
    }
    if (issue.priority !== void 0) {
      meta.createEl("span", {
        cls: "linian-card-priority",
        text: `${PRIORITY_ICONS[issue.priority] || PRIORITY_ICONS[0]} ${PRIORITY_LABELS[issue.priority] || PRIORITY_LABELS[0]}`
      });
    }
    if (issue.commentCount !== void 0) {
      const n = issue.commentCount;
      meta.createEl("span", {
        cls: "linian-card-comments",
        text: `\u{1F4AC} ${n} comment${n === 1 ? "" : "s"}`
      });
    }
    if (issue.description) {
      this.component.load();
      const descEl = contentEl.createDiv({ cls: "linian-card-description" });
      void import_obsidian3.MarkdownRenderer.render(
        this.app,
        issue.description,
        descEl,
        "",
        this.component
      );
    }
    const footer = contentEl.createDiv({ cls: "linian-card-footer" });
    const note = footer.createEl("span", { cls: "linian-card-freshness" });
    if (status === "fresh") {
      note.setText(`Updated ${formatRelative(fetchedAt)}`);
    } else if (status === "inaccessible") {
      note.addClass("linian-card-freshness--warn");
      note.setText(
        `Saved copy \u2014 no longer accessible in Linear (last updated ${formatRelative(
          fetchedAt
        )})`
      );
    } else {
      note.addClass("linian-card-freshness--warn");
      note.setText(
        `Saved copy \u2014 Linear unreachable (last updated ${formatRelative(
          fetchedAt
        )})`
      );
    }
    new import_obsidian3.ButtonComponent(footer).setButtonText("Open in Linear").setCta().onClick(() => window.open(issue.url, "_blank"));
  }
  onClose() {
    this.component.unload();
    this.contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian4 = require("obsidian");
var STALE_PRESETS = {
  "1 hour": 60 * 60 * 1e3,
  "6 hours": 6 * 60 * 60 * 1e3,
  "24 hours": 24 * 60 * 60 * 1e3
};
var LinianSettingTab = class extends import_obsidian4.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian4.Setting(containerEl).setName("Linear API key").setDesc("Generate a personal API key in Linear: Settings \u2192 API.").addText(
      (text) => text.setPlaceholder("lin_api_\u2026").setValue(this.plugin.settings.apiKey).onChange(async (value) => {
        this.plugin.settings.apiKey = value.trim();
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Test connection").setDesc("Verify the API key can reach your Linear workspace.").addButton(
      (button) => button.setButtonText("Test").onClick(async () => {
        button.setButtonText("Testing\u2026").setDisabled(true);
        const teams = await this.plugin.api.getTeams();
        if (teams.length > 0) {
          button.setButtonText("\u2713 Connected").setCta();
        } else {
          button.setButtonText("\u2717 Failed").removeCta();
        }
        window.setTimeout(() => {
          button.setButtonText("Test").setDisabled(false).removeCta();
        }, 3e3);
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Display").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Show priority icons").setDesc("Display a priority icon next to compact issue identifiers.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enablePriorityIcons).onChange(async (value) => {
        this.plugin.settings.enablePriorityIcons = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Show assignee avatars").setDesc("Display the assignee's avatar on compact issues.").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.enableAssigneeAvatars).onChange(async (value) => {
        this.plugin.settings.enableAssigneeAvatars = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Sync").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Background refresh").setDesc(
      "Quietly revalidate cached issues when they age. Cached data is always kept if a refresh fails."
    ).addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.autoRefresh).onChange(async (value) => {
        this.plugin.settings.autoRefresh = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Refresh after").setDesc("How long a cached issue stays fresh before a background refresh.").addDropdown((dropdown) => {
      var _a;
      for (const label of Object.keys(STALE_PRESETS)) {
        dropdown.addOption(label, label);
      }
      const current = (_a = Object.keys(STALE_PRESETS).find(
        (l) => STALE_PRESETS[l] === this.plugin.settings.staleAfterMs
      )) != null ? _a : "6 hours";
      dropdown.setValue(current).onChange(async (label) => {
        this.plugin.settings.staleAfterMs = STALE_PRESETS[label];
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian4.Setting(containerEl).setName("Cache").setHeading();
    new import_obsidian4.Setting(containerEl).setName("Maximum cached issues").setDesc("Least-recently-fetched issues are evicted beyond this limit.").addSlider(
      (slider) => slider.setLimits(100, 5e3, 100).setValue(this.plugin.settings.maxCacheSize).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxCacheSize = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian4.Setting(containerEl).setName("Clear cache").setDesc(
      `Delete all ${this.plugin.cache.size()} saved issue snapshots. Offline previews will be unavailable until issues are fetched again.`
    ).addButton(
      (button) => button.setButtonText("Clear").setWarning().onClick(() => {
        this.plugin.cache.clear();
        button.setButtonText("\u2713 Cleared");
        window.setTimeout(() => this.display(), 1200);
      })
    );
  }
};

// src/live-preview.ts
var import_state = require("@codemirror/state");
var import_view = require("@codemirror/view");
var import_obsidian5 = require("obsidian");
var isEditorInLivePreviewMode = (view) => view.state.field(import_obsidian5.editorLivePreviewField);
var isCursorInsideTag = (view, start, length) => {
  const cursor = view.state.selection.main.head;
  return cursor > start - 1 && cursor < start + length + 1;
};
var isSelectionContainsTag = (view, start, length) => {
  const selectionBegin = view.state.selection.main.from;
  const selectionEnd = view.state.selection.main.to;
  return selectionEnd > start - 1 && selectionBegin < start + length + 1;
};
var LinearIssueWidget = class extends import_view.WidgetType {
  constructor(key, controller, displayMode) {
    super();
    this.key = key;
    this.controller = controller;
    this.displayMode = displayMode;
    this._container = document.createElement("span");
    this._container.className = "linian-inline-issue linian-container";
    this.controller.render(this._container, this.key, this.displayMode);
  }
  eq(other) {
    return other.key === this.key && other.displayMode === this.displayMode;
  }
  toDOM() {
    return this._container;
  }
  destroy() {
    this._container.replaceChildren();
  }
};
function buildMatchDecorator(controller) {
  return new import_view.MatchDecorator({
    regexp: LINEAR_SHORTCODE_REGEX,
    decoration: (match, view, pos) => {
      const displayMode = match[1] ? "expanded" : "compact";
      const key = match[2];
      const tagLength = match[0].length;
      if (!isEditorInLivePreviewMode(view) || isCursorInsideTag(view, pos, tagLength) || isSelectionContainsTag(view, pos, tagLength)) {
        return import_view.Decoration.mark({
          tagName: "span",
          class: "linian-shortcode-highlight"
        });
      }
      return import_view.Decoration.replace({
        widget: new LinearIssueWidget(key, controller, displayMode)
      });
    }
  });
}
function buildViewPlugin(decorator) {
  class ViewPluginClass {
    constructor(view) {
      this.decorators = decorator.createDeco(view);
    }
    update(update) {
      const editorModeChanged = update.startState.field(
        import_obsidian5.editorLivePreviewField
      ) !== update.state.field(
        import_obsidian5.editorLivePreviewField
      );
      if (update.docChanged || update.startState.selection.main !== update.state.selection.main || editorModeChanged) {
        this.decorators = decorator.createDeco(update.view);
      }
    }
    destroy() {
      this.decorators = import_state.RangeSet.empty;
    }
  }
  const spec = {
    decorations: (viewPlugin) => viewPlugin.decorators
  };
  return import_view.ViewPlugin.fromClass(ViewPluginClass, spec);
}
var LinearViewPluginManager = class {
  constructor() {
    this._viewPlugin = null;
  }
  setController(controller) {
    this._viewPlugin = buildViewPlugin(buildMatchDecorator(controller));
  }
  getViewPlugin() {
    return this._viewPlugin;
  }
};

// main.ts
var LinianPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.cache = new IssueCacheStore(this, this.settings.maxCacheSize);
    await this.cache.load();
    this.api = new LinearAPIService(this.settings.apiKey);
    this.renderer = new LinearRenderer(this.settings);
    this.controller = new IssueController(
      this.api,
      this.cache,
      this.renderer,
      () => this.settings,
      (entry) => new IssueCard(this.app, entry).open()
    );
    this.addSettingTab(new LinianSettingTab(this.app, this));
    this.registerMarkdownPostProcessor(
      this.processLinearShortcodes.bind(this)
    );
    this.viewPluginManager = new LinearViewPluginManager();
    this.viewPluginManager.setController(this.controller);
    const viewPlugin = this.viewPluginManager.getViewPlugin();
    if (viewPlugin)
      this.registerEditorExtension(viewPlugin);
    this.addCommand({
      id: "refresh-linear-cache",
      name: "Refresh Linear cache",
      callback: () => {
        this.controller.resetSessionGuard();
        this.app.workspace.updateOptions();
      }
    });
  }
  async onunload() {
    if (this.cache)
      await this.cache.flushNow();
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    var _a, _b, _c;
    await this.saveData(this.settings);
    (_a = this.renderer) == null ? void 0 : _a.updateSettings(this.settings);
    (_b = this.api) == null ? void 0 : _b.updateApiKey(this.settings.apiKey);
    (_c = this.cache) == null ? void 0 : _c.setMaxSize(this.settings.maxCacheSize);
    this.app.workspace.updateOptions();
  }
  processLinearShortcodes(element, _context) {
    var _a, _b, _c, _d;
    const walker = document.createTreeWalker(element, NodeFilter.SHOW_TEXT);
    const textNodes = [];
    while (walker.nextNode()) {
      const current = walker.currentNode;
      if (!((_a = current.nodeValue) == null ? void 0 : _a.length))
        continue;
      if ((_b = current.parentElement) == null ? void 0 : _b.closest(".linian-inline-issue"))
        continue;
      textNodes.push(current);
    }
    for (const textNode of textNodes) {
      const sourceText = (_c = textNode.nodeValue) != null ? _c : "";
      const regex = createShortcodeRegex();
      const fragment = document.createDocumentFragment();
      const pending = [];
      let match;
      let lastIndex = 0;
      let hasMatch = false;
      while ((match = regex.exec(sourceText)) !== null) {
        hasMatch = true;
        const preceding = sourceText.slice(lastIndex, match.index);
        if (preceding)
          fragment.appendChild(document.createTextNode(preceding));
        const mode = match[1] ? "expanded" : "compact";
        const container = document.createElement("span");
        container.className = "linian-inline-issue linian-container";
        fragment.appendChild(container);
        pending.push({ container, key: match[2], mode });
        lastIndex = regex.lastIndex;
      }
      if (!hasMatch)
        continue;
      const trailing = sourceText.slice(lastIndex);
      if (trailing)
        fragment.appendChild(document.createTextNode(trailing));
      (_d = textNode.parentNode) == null ? void 0 : _d.replaceChild(fragment, textNode);
      for (const { container, key, mode } of pending) {
        this.controller.render(container, key, mode);
      }
    }
  }
};
