name: Test Release

on:
  push:
    tags:
      - "test-*"

jobs:
  test-build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: List files
        run: ls -la

      - name: Create test release
        uses: softprops/action-gh-release@v1
        with:
          name: "Test Release ${{ github.ref_name }}"
          body: "Test release to debug workflow issues"
          files: |
            main.js
            manifest.json
            styles.css
